# PostgreSQL. Versions 9.1 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: psqluser
  password: changeit
  host: localhost
  port: 5432

development:
  <<: *default
  database: finance-development

test:
  <<: *default
  database: finance-test

production:
  <<: *default
  database: finance-production
  username: finance-tracker
  password: <%= ENV['FINANCE-TRACKER_DATABASE_PASSWORD'] %>